services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: openisle-mysql
    restart: always
    env_file:
      - ../backend/open-isle.env
      - ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../backend/src/main/resources/db/init:/docker-entrypoint-initdb.d
    networks:
      - openisle-network
  
  # OpenSearch Service
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensearch
    environment:
      - cluster.name=os-single
      - node.name=os-node-1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - DISABLE_SECURITY_PLUGIN=true
      - cluster.blocks.create_index=false
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    volumes:
      - ./data:/usr/share/opensearch/data
      - ./snapshots:/snapshots
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: os-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    restart: unless-stopped


  # Java spring boot service
  springboot:
    image: maven:3.9-eclipse-temurin-17
    container_name: openisle-springboot
    working_dir: /app
    env_file:
      - ../backend/open-isle.env
      - ./.env
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=yes&characterEncoding=UTF-8&useInformationSchema=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ../backend:/app
      - maven-repo:/root/.m2
    depends_on:
      - mysql
    command: mvn clean spring-boot:run -Dmaven.test.skip=true
    networks:
      - openisle-network

networks:
  openisle-network:
    driver: bridge

volumes:
  mysql-data:
  maven-repo:
